### ISSUE TITLE
alpine doesn't have usermod

### ISSUE THREAD

**Issue by ghost** [pstauffer/docker-bind#6]
/named.sh: line 22: usermod: not found
/named.sh: line 23: groupmod: not found

**Comment by pstauffer** [comment]
Hi @majoux ,

Thanks for the feedback. I've implemented a solution #11 and pushed it to the branch  `develop`.
Please check out this tag on docker hub and try, if it's working now for you. I've tested it on my box and it seems to work. It's sad, that usermod / groupmod is not available on busybox/alpine, so I delete the group/user and create it with the new uid/gid.

I will check the other pull requests tomorrow.

Greets
Pascal

**Comment by pstauffer** [comment]
Fixed in develop branch
